### ISSUE TITLE
Start clima

### ISSUE THREAD

**Issue by romanmatyus** [karlsen-technologies/volkswagen-php#1]
Hello, it's very nice work!

Please, can You please help me with:

```php
$ic = new KarlsenTechnologies\Volkswagen\IdentityClient;
$c = new KarlsenTechnologies\Volkswagen\WeConnectClient;
$c->login($ic->authorize('romanmatyus@gmail.com', 'Asdf1234faq'));

foreach ($c->vehicles() as $v) {
	$c->startClimatisation($v);
}
```
I receive:

```
PHP Fatal error:  Uncaught KarlsenTechnologies\Volkswagen\Exceptions\BadRequestException: Internal error, please try again later. If the problem persists, please contact our support. in /home/roman/htdocs/volkswagen-php/vendor/karlsen-technologies/volkswagen-php/src/BaseClient.php:81
```

Thanks!

**Comment by romanmatyus** [comment]
This working:

```php
$c->startClimatisation($v, new ClimatisationSettings(
    true,
    30,
    ClimatisationTemperatureUnit::Celsius,
    true,
    null,
    true,
    true,
    true,
    true,
    true,
));
```

**Comment by thomasakarlsen** [comment]
I see you figured out the fix yourself 🙂

I've not yet implemented or documented the requirements each endpoint has on the Volkswagen side of things. 
Their start climatisation endpoint require the `targetTemperature`, `targetTemperatureUnit` and I belive `climatisationWithoutExternalPower` aswell to be provided when you do a request.

Thank you for the interest in this SDK, its still a work in progress 😄

**Comment by thomasakarlsen** [comment]
As a side note; if you want your code to look cleaner you can also provide the options to the `startClimatisation` function as an array, including only the options you want to use. See [the toApi() function](https://github.com/karlsen-technologies/volkswagen-php/blob/c9e58053df5fd77ed6902a63697511a851220a9e/src/DataObjects/Vehicle/Climatisation/ClimatisationSettings.php#L24) in the ClimatisationSettings data object for more details on the valid array keys
