### ISSUE TITLE
Trips paging

### ISSUE THREAD

**Issue by romanmatyus** [karlsen-technologies/volkswagen-php#2]
Please, do you know, how is in API implemented paging? For example for calling:

```php
$response = $this->get("/vehicle/v1/trips/{$vehicle}/shortterm");
```

I receive only last 50 trips.

Thanks!

**Comment by thomasakarlsen** [comment]
I recently reconnected my car with WeConnect so I do not have a trip log long enough to properly test with, but I do know that you can use the query parameters `from` and `to` to limit what results you get. 

Example:
`/vehicle/v1/trips/{$vehicle}/shortterm?from=2024-01-27T23:00:00.000Z&to=2024-02-28T22:59:59.999Z`

I've not yet started to work with that endpoint, but from the little I checked I cant see any traces of proper pagination options. Could be we just need to use the from/to parameters to "paginate" ourselves.
